# Soon
version: "3.9"

services:
  db:
    image: postgres:15
    container_name: evidex_postgres
    restart: always

    environment:
      POSTGRES_DB: evidex
      POSTGRES_USER: evidex_user
      POSTGRES_PASSWORD: evidex_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
    