# Generated by Django 6.0 on 2026-01-16 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_alter_report_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfinding',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportfinding',
            name='impact',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportfinding',
            name='remediation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportfinding',
            name='severity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reportfinding',
            name='vulnerability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_findings', to='knowledge.vulnerabilitydefinition'),
        ),
    ]
