# Generated by Django 6.0 on 2026-01-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_alter_reportfinding_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfinding',
            name='tester_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportfinding',
            name='tester_impact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportfinding',
            name='tester_remediation',
            field=models.TextField(blank=True),
        ),
    ]
