# Generated by Django 6.0 on 2026-01-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_reportfinding_tester_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfinding',
            name='tester_severity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reportfinding',
            name='tester_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reportfinding',
            name='severity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reportfinding',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
