# Generated by Django 6.0 on 2026-01-16 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_reportfinding_tester_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfinding',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='knowledge.report'),
        ),
    ]
