# Generated by Django 6.0 on 2026-01-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='target',
            field=models.CharField(default='example.com', max_length=255),
            preserve_default=False,
        ),
    ]
