# Generated by Django 6.0 on 2026-01-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0011_report_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='target',
        ),
    ]
