# Generated by Django 6.0 on 2026-01-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0013_report_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfinding',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Patched', 'Patched')], default='Pending', max_length=20),
        ),
    ]
