# Generated by Django 6.0 on 2026-02-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0014_reportfinding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='approved_by',
            field=models.CharField(blank=True, default='test', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewer',
            field=models.CharField(blank=True, default='test', max_length=150, null=True),
        ),
    ]
