# Generated by Django 6.0 on 2026-02-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0015_report_approved_by_report_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reviewer',
        ),
    ]
