# Generated by Django 6.0 on 2026-02-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0016_remove_report_approved_by_remove_report_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='test_location',
            field=models.CharField(default='Off-site', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='target',
            field=models.TextField(),
        ),
    ]
