# Generated by Django 6.0 on 2026-02-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0017_report_test_location_alter_report_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tools_used',
            field=models.TextField(blank=True, default=''),
        ),
    ]
