# Generated by Django 6.0 on 2026-02-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0018_report_tools_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
