# Generated by Django 6.0 on 2026-03-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0019_report_approved_by_report_reviewed_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='findingevidence',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='findingevidence',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
