# Generated by Django 6.0 on 2026-03-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0021_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingevidence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reportfinding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
