# Generated by Django 6.0 on 2026-03-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0023_findingevidence_updated_by_report_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfinding',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Patched', 'Patched'), ('False Positive', 'False Positive')], default='Pending', max_length=20),
        ),
    ]
