# Generated by Django 6.0 on 2026-03-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0026_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
