# Generated by Django 6.0 on 2026-03-31 15:58

from django.db import migrations, models


def migrate_verified_to_approved(apps, schema_editor):
    Report = apps.get_model('knowledge', 'Report')
    Report.objects.filter(status='verified').update(status='approved')
    
    AuditLog = apps.get_model('knowledge', 'AuditLog')
    AuditLog.objects.filter(old_value='verified').update(old_value='approved')
    AuditLog.objects.filter(new_value='verified').update(new_value='approved')

def reverse_migrate(apps, schema_editor):
    Report = apps.get_model('knowledge', 'Report')
    Report.objects.filter(status='approved').update(status='verified')
    
    AuditLog = apps.get_model('knowledge', 'AuditLog')
    AuditLog.objects.filter(old_value='approved').update(old_value='verified')
    AuditLog.objects.filter(new_value='approved').update(new_value='verified')

class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0027_alter_report_status'),
    ]

    operations = [
        migrations.RunPython(migrate_verified_to_approved, reverse_migrate),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved')], default='in_progress', max_length=20),
        ),
    ]
