# Generated by Django 6.0 on 2026-04-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0028_rename_verified_to_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('EXPORT_PDF', 'Export PDF'), ('EXPORT_DOCX', 'Export DOCX'), ('EMAIL_SENT', 'Email Sent'), ('ROLE_CHANGE', 'Role Change'), ('USER_MANAGEMENT', 'User Management'), ('SECURITY_EVENT', 'Security Event')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='report_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
